version: "3"

networks: 
    laravel:

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - "8080:80"
        volumes: 
            - ./src/:/var/www/html/
            - ./nginx/logs/:/var/log/nginx
            - ./nginx/configs/:/etc/nginx/conf.d/
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel


    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "33061:3306"
        volumes: 
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
        networks: 
            - laravel


    php:
        build: 
            context: .
            dockerfile: DockerfilePhp
        container_name: php
        volumes: 
            - ./src:/var/www/html
        ports: 
            - "9000:9000"
        networks: 
            - laravel